<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Logo_DuocUC.svg/2560px-Logo_DuocUC.svg.png' width=50%, height=20%>

# Introducción

Matrices y Aritmetica de Matrices para Machine Learning
Extracto de código generado por Jason Brownlee
*
## Para este ejercicio usaremos la biblioteca NUMPY

NumPy es una librería de Python para computación científica. NumPy significa  Python numérico. 

El principal beneficio de NumPy es que permite una generación y manejo de datos extremadamente rápido. NumPy tiene su propia estructura de datos incorporada llamado arreglo que es similar a la lista normal de Python, pero puede almacenar y operar con datos de manera mucho más eficiente.

Hay dos tipos diferentes de arreglos de NumPy: vectores y matrices.




In [1]:
# creación de matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [2]:
# suma de matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [3]:
# resta de matrices matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]])
print(B)
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


# Producto Hadamart o multiplicación de matrices
Dos matrices con el mismo tamaño se pueden multiplicar juntas, y esto a menudo se denomina multiplicación de matrices por elementos o producto de Hadamard.

.

In [4]:
# element-wise multiply matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [5]:
# divide matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Producto PUNTO.

La multiplicación de matrices, también llamada producto escalar de matrices, implica una regla, ya que no todas las matrices se pueden multiplicar juntas.

La regla para la multiplicación de matrices es la siguiente:

***El número de columnas (n) de la primera matriz (A) debe ser igual al número de filas (m) de la segunda matriz (B).***

Esta regla se aplica a una cadena de multiplicaciones de matrices en las que el número de columnas de una matriz de la cadena debe coincidir con el número de filas de la siguiente matriz de la cadena.

***Una de las operaciones más importantes que involucran matrices es la multiplicación de dos matrices. El producto matricial de las matrices A y B es una tercera matriz C. Para que se defina este producto, A debe tener el mismo número de columnas que B tiene filas. Si A tiene forma m × n y B tiene forma n × p, entonces C tiene forma m × p.***

— Página 34, Deep Learning, 2016.

In [6]:
# producto punto
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
B = array([[1, 2], [3, 4]])
print(B)
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


In [7]:
# multiplicación de vector por matriz
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
B = array([0.5, 0.5])
print(B)
C = A.dot(B)
print(C)
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]
[1.5 3.5 5.5]


In [8]:
# multiplicación de escalar por matriz
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
b = 0.5
print(b)
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


SISTEMAS DE ECUACIONES LINEALES

Para resolver un sistema de ecuaciones lineales, necesitamos realizar dos operaciones: inversión de matriz y un producto escalar de matriz. La biblioteca Numpy de Python admite ambas operaciones.

Resolvamos el siguiente sistema de ecuaciones lineales:

In [ ]:
# 4x  + 3y = 20
# -5x + 9y = 26


En el siguiente script, creamos una lista llamada m_list, que además contiene dos listas: [4,3] y [-5,9]. Estas listas son las dos filas de la matriz A. Para crear la matriz A con Numpy, m_list se pasa al método array como se muestra a continuación:

In [9]:
import numpy as np
m_list = [[4, 3], [-5, 9]]
A = np.array(m_list)

Para encontrar la inversa de una matriz, la matriz se pasa al método linalg.inv() del módulo Numpy:

In [10]:
inv_A = np.linalg.inv(A)

print(inv_A)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


El siguiente paso es encontrar el producto punto entre la inversa de la matriz ‘A’ y la matriz ‘B’. Es importante mencionar que el producto punto de matrices solo es posible entre las matrices si las dimensiones internas de las matrices son iguales, es decir, el número de columnas de la matriz de la izquierda debe coincidir con el número de filas de la matriz de la derecha.

Para encontrar el producto punto con la biblioteca Numpy, se usa la función linalg.dot(). El siguiente script encuentra el producto punto entre la inversa de la matriz A y la matriz B.

In [11]:
B = np.array([20, 26])
X = np.linalg.inv(A).dot(B)

print(X)

[2. 4.]


Aquí, 2 y 4 son los valores respectivos para las incógnitas x e y en la ecuación. Para verificar, si insertas 2 en lugar de la incógnita x y 4 en lugar de la incógnita y en la ecuación 4x + 3y, verás que el resultado será 20.

Resolvamos ahora un sistema de tres ecuaciones lineales, como se muestra a continuación:

In [ ]:
# 4x + 3y + 2z = 25
# -2x + 2y + 3z = -10
# 3x -5y + 2z = -4


La ecuación anterior se puede resolver usando la biblioteca Numpy de la siguiente manera:

In [ ]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.inv(A).dot(B)

print(X)


El valor de las incógnitas x, y y z son 5, 3 y -2, respectivamente. Puede introducir estos valores en Ecuación 2 y verificar su exactitud.

## Método Solved
En los dos ejemplos anteriores, usamos los métodos linalg.inv() y linalg.dot() para encontrar la solución del sistema de ecuaciones. Sin embargo, la biblioteca Numpy contiene el método linalg.solve(), que se puede usar para encontrar directamente la solución de un sistema de ecuaciones lineales:

In [ ]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X2 = np.linalg.solve(A,B)

print(X2)


## EJERCICIO

Suponga que un vendedor de frutas vendió 20 mangos y 10 naranjas en un día por un total de $350. Al día siguiente vendió 17 mangos y 22 naranjas por $350.

Al dıa siguiente vendio 17mangos y 22 naranjas por $500.

Si los precios de las frutas permanecieron sin cambios en ambos días, ¿cuál fue el precio de un mango y una naranja?


In [2]:
# definimos las matrices
import numpy as np
a = np.array([[20, 10], 
              [17, 22]])
b = np.array([350, 500])

# resolvemos el sistema de ecuaciones
x = np.linalg.solve(a, b)

print(f"el precio del mango es {x[0].round()}")
print(f"el precio las naranjas es {x[1].round()}")

el precio del mango es 10.0
el precio las naranjas es 15.0
